#!/usr/bin/env python3
import sys

grid = []
for i in range(20):
    grid.append(input())
grid.append('###########') 

for col in range(10):
    i = 0
    while grid[i][col] != '#':
        i += 1
    if i < 4:
        continue
    if all(grid[r].count('#') == 9 for r in range(i-4, i)):
        print('BOOM ' + str(col+1))
        break
print('NOPE')
