#!/usr/bin/env python3
import sys

all_friend = {}
for line in sys.stdin:
    lines = line.rstrip('\n')
    actual = lines.split(" ")
    if len(actual) != 2:
        continue
    try:
        all_friend[actual[0]] += 1
    except:
        all_friend[actual[0]] = 1
    try:
        all_friend[actual[1]] += 1
    except:
        all_friend[actual[1]] = 1

best_v = 0
for value in all_friend.values():
    if value > best_v:
        best_v = value

print(best_v)