#!/usr/bin/env python3
import sys

lines = []
for line in sys.stdin:
	lines.append(line.rstrip('\n'))

dico = {}

for i in lines:
    try:
        dico[i] += 1
    except:
        dico[i] = 1
        
for key,value in dico.items():
    if value == 2:
        print(key)